apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: anranpod2
  namespace: dev
spec:
  selector:
    matchLabels:
      app: anranpod2
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: anranpod2
    spec:
      containers:
      - name: anranpod2
        image: registry-vpc.cn-shanghai.aliyuncs.com/cr_namespace-k8sapp/cr-repo-k8sapp:${version} # use sed replace
        ports:
        - containerPort: 80
        - containerPort: 8080