apiVersion: v1
kind: Service
metadata:
  name: arpod-svc2
  namespace: dev
spec:
  ports:
    - name: portmap
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: anranpod2
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
