apiVersion: v1
kind: Service
metadata:
  creationTimestamp: '2020-11-09T02:13:50Z'
  name: arpod-svc
  namespace: arms-prom
  resourceVersion: '54821377'
  selfLink: /api/v1/namespaces/arms-prom/services/arpod-svc
  uid: c73bb9c6-32fb-4da3-b5eb-5906063e9126
spec:
  ports:
    - name: portmap
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: anrandeployment
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
